### PR TITLE
SDGophers 9/21 Sudoku Solver Solution

### PR DESCRIPTION
**Pull request by ggrpmnn**
Hi all! This PR is for the solution that I and @srh came up with. It includes the `main.go` file with all the executable code, as well as `extreme_1_puzzle.txt` and `extreme_1_puzzle_solution.txt` - a puzzle and it's solution designed to work against the algorithm we implemented (according to [Wikipedia](https://en.wikipedia.org/wiki/Sudoku_solving_algorithms)).

### CODE REVIEW

**Comment by carlisia** [comment]
Hi @ggrpmnn! What if you namespace your solution to a separate folder, so we can have multiple solutions checked in? Maybe namespace by your username? And thanks for submitting, this is awesome!

**Comment by ggrpmnn** [comment]
Sure, I'll do that this evening. Thanks for the suggestion!

**Comment by ggrpmnn** [comment]
Sorry for the delay! I have made the move, and the `main.go` file for our solution is now under a new dir (`srh_and_ggrpmnn/`).

**Comment by carlisia** [comment]
👍

**Pull request merged**
